name: CI/CD - Development

env:
  GLOBAL_ENV: "workflow-level-dev"

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development
      DEPLOY_ENV: dev
      JOB_ENV: "job-level-dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Print Workflow and Job Env
        run: |
          echo "GLOBAL_ENV = $GLOBAL_ENV"
          echo "JOB_ENV = $JOB_ENV"
          echo "NODE_ENV = $NODE_ENV"
          echo "DEPLOY_ENV = $DEPLOY_ENV"

      # 🔹 STEP-level environment variable
      - name: Step-level variable
        run: echo "STEP_ENV = $STEP_ENV"
        env:
          STEP_ENV: "step-level-dev"

      - name: Run tests
        run: npm test

      - name: Deploy to Dev Environment
        run: echo "Deploying to DEV with token ${{ secrets.DEV_TOKEN }}"
